---
title: "regmedint"
author: "Chun-Hui Lin"
date: "2025-02-11"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Some notes on conducting causal mediation analysis with time-to-event outcomes. Since `gsem` from Stata did not support Cox as outcome model, [`regmedint`](https://kaz-yos.github.io/regmedint/) was utilized instead. 

```{r, echo=FALSE, warning=FALSE}
# install.packages('regmedint')
library(regmedint)
```

* `regmedint()`

  * `yvar` argument: outcome variable name (time variable for survival outcome).
  * `eventvar` argument: event variable for survival outcome.
  * `avar` argument: treatment variable name.
  * `mvar` argument: mediator variable name.
  * `cvar` argument: covariate names.
  * `a0` argument: "untreated"; the reference level of treatment variable.
  * `a1` argument: "treated".
  * `m_cde` argument: mediator level at which controlled direct effect is evaluated at.
  * `c_cond` argument: covariate level at which natural direct and indirect effects are evaluated at.
  * `mreg` argument: mediator regression type.
  * `yreg` argument: outcome regression type.

